services:
  llm:
    container_name: lingua-llm-dev
    image: lingua-llm:${BRANCH:-dev}
    build:
      context: ../llm
      dockerfile: Dockerfile
    depends_on:
      - ai
    restart: always
    expose:
      - '5201'
    networks:
      - lingua-dev

  postgres:
    container_name: postgres-ai-dev
    image: postgres:16.1-alpine3.19
    environment:
      - POSTGRES_DB=pg-lingua-ai
      - POSTGRES_PASSWORD=${PG_PSW}
      - POSTGRES_USER=lingua-ai
    volumes:
      - /var/lib/postgresql/lingua-ai-dev/data:/var/lib/postgresql/data
      - type: bind
        source: /home/alex/DockerShareFiles
        target: /home/dump
    expose:
      - '5433'
    ports:
      - '6433:5433'
    networks:
      - lingua-dev

  ai:
    container_name: lingua-ai-dev
    image: lingua-ai:${BRANCH:-dev}
    build:
      context: ../.
      dockerfile: Dockerfile
      args:
        config_dir: ${CONFIG:-docker/server.dev}
        pg_psw: ${PG_PSW}
        branch: ${BRANCH}
        commit: ${COMMIT}
      additional_contexts:
        root: /
    volumes:
      - type: bind
        source: /home/alex/DockerShareFiles
        target: /lingua-evo/logs
    depends_on:
      - postgres
    restart: always
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    expose:
      - '5100'
    ports:
      - '5100:5100'
    networks:
      - lingua-dev

  migration:
    container_name: migration-dev
    image: migration:${BRANCH:-dev}
    build:
      context: ../migration
    depends_on:
      - postgres
    networks:
      - lingua-dev
    entrypoint:
      - '/bin/sh'
      - '-ecx'
      - './migration -cmd ${CMD:-up} -url lingua:${PG_PSW}@postgres-ai-dev:5432/pg-lingua-evo?sslmode=disable'

networks:
  lingua-dev:
    name: lingua-dev
