services:
  minio:
    container_name: minio-ai-dev
    image: minio/minio:latest
    restart: always
    expose:
      - '9000'
      - '9001'
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      - MINIO_ROOT_USER=lingua-minio
      - MINIO_ROOT_PASSWORD=${MINIO_PSW}
    command: server /data --console-address ":9001"
    volumes:
      - /var/lib/minio/lingua-ai-dev/data:/data
    networks:
      - lingua-dev

  ai:
    container_name: lingua-ai-dev
    image: lingua-ai:${BRANCH:-dev}
    build:
      context: ../.
      dockerfile: Dockerfile
      args:
        config_dir: ${CONFIG:-docker/server.dev}
        pg_psw: ${PG_PSW}
        minio_psw: ${MINIO_PSW}
        branch: ${BRANCH}
        commit: ${COMMIT}
      additional_contexts:
        root: /
    volumes:
      - type: bind
        source: /home/alex/DockerShareFiles
        target: /lingua-ai/logs
    depends_on:
      - minio
    restart: always
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    expose:
      - '5100'
    ports:
      - '5100:5100'
    networks:
      - lingua-dev

networks:
  lingua-dev:
    name: lingua-dev
