services:
  minio:
    container_name: minio-ai-dev
    image: minio/minio:latest
    depends_on:
      - ai
    restart: always
    expose:
      - '9000'
      - '9001'
    environment:
      - MINIO_ROOT_USER=lingua-minio
      - MINIO_ROOT_PASSWORD=${MINIO_PSW}
    networks:
      - lingua-dev

  postgres:
    container_name: postgres-ai-dev
    image: postgres:16.1-alpine3.19
    environment:
      - POSTGRES_DB=pg-lingua-ai
      - POSTGRES_PASSWORD=${PG_PSW}
      - POSTGRES_USER=lingua-ai
    volumes:
      - /var/lib/postgresql/lingua-ai-dev/data:/var/lib/postgresql/data
      - type: bind
        source: /home/alex/DockerShareFiles
        target: /home/dump
    expose:
      - '5432'
    ports:
      - '6432:5432'
    networks:
      - lingua-dev

  ai:
    container_name: lingua-ai-dev
    image: lingua-ai:${BRANCH:-dev}
    build:
      context: ../.
      dockerfile: Dockerfile
      args:
        config_dir: ${CONFIG:-docker/server.dev}
        pg_psw: ${PG_PSW}
        minio_psw: ${MINIO_PSW}
        branch: ${BRANCH}
        commit: ${COMMIT}
      additional_contexts:
        root: /
        # volumes:
        #- type: bind
        #   source: /home/alex/DockerShareFiles
        #   target: /lingua-ai/logs
        # depends_on:
        #   - postgres
    restart: always
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    expose:
      - '5100'
    ports:
      - '5100:5100'
    networks:
      - lingua-dev

  migration:
    container_name: migration-ai-dev
    image: migration:${BRANCH:-dev}
    build:
      context: ../migration
    depends_on:
      - postgres
    networks:
      - lingua-dev
    entrypoint:
      - '/bin/sh'
      - '-ecx'
      - './migration -cmd ${CMD:-up} -url lingua-ai:${PG_PSW}@postgres-ai-dev:5432/pg-lingua-ai?sslmode=disable'

networks:
  lingua-dev:
    name: lingua-dev
