pprof_debug:
    enable: true
    port: 6060
logger:
    output:
        - console
    level: debug
    server_level: debug
service:
    port: 5001
    allowed_origins:
        - "http://localhost:5000"
    enable_swagger: true
postgres:
    name: pg-lingua-evo
    user: lingua
    host: localhost
    port: 6432
    max_conns: 10
    min_conns: 0
    max_conn_life_time: 3600
    max_conn_idle_time: 1800
    health_check_period: 60
    connect_timeout: 5
tts:
    models:
        en:
            vits-model: ../llm/vits-piper-en_US-lessac-medium/en_US-lessac-medium.onnx
            vits-lexicon: ../llm/vits-vctk/lexicon.txt
            vits-tokens: ../llm/vits-piper-en_US-lessac-medium/tokens.txt
            vits-data-dir: ../llm/vits-piper-en_US-lessac-medium/espeak-ng-data
            vits-noise-scale: 0.667
            vits-noise-scale-w: 0.8
            vits-length-scale: 1.0
    num-threads: 1
    debug: 1 
    provider: cpu
    tts-rule-fsts: ''
    tts-rule-fars: ''
    tts-max-num-sentences: 1
    sid: 0
